connector.name=postgresql
connection-url=jdbc:postgresql://{{ pgHosts }}/datart?currentSchema=datart&targetServerType=primary&loadBalanceHosts=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
connection-user={{ pgUser }}
connection-password={{ pgPassword }}
